version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: syncdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: python app.py

volumes:
  db-data:
